version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY}api
    build:
      context: ../
      dockerfile: ./deploy/IdentityService.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9000:80"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"